WebApp/Controllers/PublicacionController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio1;
using WebApp.Filtros;


namespace WebApp.Controllers
{
    public class PublicacionController : Controller
    {
        private Sistema _sistema = Sistema.Instancia;

        [Admin]
        public IActionResult Index()
        {
            ViewData["Posts"] = _sistema.ListarTodasLosPost();
            return View();
        }

        public IActionResult VistaPublicar()
        {
            return View();
        }

        public IActionResult BuscarPost()
        {
            return View();
        }

        public IActionResult EncontrarPost()
        {
            return View();
        }

        [Miem]
        [HttpPost]
        public IActionResult Postear(string titulo, string contenido, string img, string estado)
        {

            string email = HttpContext.Session.GetString("email");
            string rol = HttpContext.Session.GetString("rol");

            try
            {
                Miembro miembro = _sistema.ObtenerMiembro(email);
                if (miembro.Bloqueado==false)
                {
                    if (titulo!=null)
                    {
                        if (contenido!=null)
                        {
                            if (img!=null)
                            {
                                if (estado!=null)
                                {
                                    bool esPublico = false;
                                    if (estado == "publico")
                                    {
                                        esPublico = true;
                                    }
                                    DateTime fechaActual = new DateTime();
                                    fechaActual = DateTime.Now;

                                    Post post5 = new Post(contenido, fechaActual, miembro, titulo, img, estado, false, esPublico);
                                    _sistema.CrearNuevoPost(post5);

                                    return RedirectToAction("Saludo", "Usuario");
                                }
                                else
                                {
                                    throw new Exception($"El estado es requerido");
                                }
                            }
                            else
                            {
                                throw new Exception($"La imagen es requerido");
                            }
                        }
                        else
                        {
                            throw new Exception($"El contenido es requerido");
                        }
                    }
                    else
                    {
                        throw new Exception($"El titulo es requerido");
                    }
                }
                else
                {
                    throw new Exception($"No se puede realizar posteos tiene la cuenta bloqueada");
                }
            }
            catch (Exception e)
            {
                ViewBag.error = e.Message;
                return View("VistaPublicar");
            }
        }

        [Miem]
        [HttpPost]
        public IActionResult Comentar(string titulo, string objetoComentario, string comentario)
        {
            string email = HttpContext.Session.GetString("email");
            string rol = HttpContext.Session.GetString("rol");

            Miembro miembro = _sistema.ObtenerMiembro(email);
            try
            {
                if (miembro.Bloqueado==false)
                {
                    if (objetoComentario != null)
                    {
                        if (titulo != null)
                        {
                            if (comentario != null)
                            {
                                Post unPost = (Post)_sistema.ObtenerPublicacion(objetoComentario);
                                DateTime fechaActual = new DateTime();
                                fechaActual = DateTime.Now;

                                Comentario nuevoComentario = new Comentario(unPost, comentario, fechaActual, miembro, titulo, unPost.EsPublico);
                                _sistema.CrearNuevoComentario(nuevoComentario);
                                unPost.AsociarComentario(nuevoComentario);

                                return RedirectToAction("Saludo", "Usuario");
                            }
                            else
                            {
                                throw new Exception($"El comentario es requerido");
                            }
                        }
                        else
                        {
                            throw new Exception($"El titulo es requerido");
                        }
                    }
                    else
                    {
                        throw new Exception($"El objeto Post no esta referenciado");
                    }
                }
                else
                {
                    throw new Exception($"No se puede realizar comentarios tiene la cuenta bloqueada");
                }
            }catch (Exception e)
            {
                return RedirectToAction("Saludo", "Usuario", new{ error= e.Message});
            }
        }

        [Admin]
        [HttpPost]
        public IActionResult Bloquear(string id)
        {
            try
            {
                if (id!=null)
                {
                    Post unPost = (Post)_sistema.ObtenerPublicacion(id);
                    unPost.Censurado = true;
                    return RedirectToAction("Index");
                }
                else
                {
                    throw new Exception($"El objeto Post es requerido");
                }
            }
            catch (Exception e)
            {

                ViewBag.error = e.Message;
                return View("Index");
            }

        }

        [Admin]
        [HttpPost]
        public IActionResult Desbloquear(string id)
        {

            try
            {
                if (id != null)
                {
                    Post unPost = (Post)_sistema.ObtenerPublicacion(id);
                    unPost.Censurado = false;
                    return RedirectToAction("Index");
                }
                else
                {
                    throw new Exception($"El objeto Post es requerido");
                }
            }
            catch (Exception e)
            {

                ViewBag.error = e.Message;
                return View("Index");
            }
            
        }

    }
}

WebApp/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Obligatorio1;
using WebApp.Filtros;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace WebApp.Controllers
{
    public class UsuarioController : Controller
    {
        private Sistema _sistema = Sistema.Instancia;


        public IActionResult Index()
        {
            string email = HttpContext.Session.GetString("email");
            string rol = HttpContext.Session.GetString("rol");

            if (email != null)
            {
                return RedirectToAction("Saludo");
            }

            return View();
        }

        public IActionResult Saludo(string error = "")
        {
            if (error != "")
            {
                ViewBag.error = error;
            }
            string email = HttpContext.Session.GetString("email");
            // Obtengo el nombre de usuario desde el correo electrónico
            string nombreUsuario = email.Split('@')[0];
            string rol = HttpContext.Session.GetString("rol");

            Miembro unMiem = _sistema.ObtenerMiembro(email);

            // Paso el nombre de usuario a la vista
            ViewData["NombreUsuario"] = nombreUsuario;

            if (rol != null && rol == "miem")
            {
                List<Post> ListPublicacion = _sistema.ListarTodasLosPost();

                if (ListPublicacion.Count != 0)
                {
                    List<Comentario> comentarios = new List<Comentario>();

                    List<Post> post = new List<Post>();

                    foreach (Post unPost in ListPublicacion)
                    {
                        if (unPost.Miembro.Bloqueado == false && unPost.Censurado == false)
                        {
                            if (unMiem == unPost.Miembro)
                            {
                                post.Add(unPost);
                                List<Comentario> comenPostAmigo = unPost.ListaDeComentarios();

                                foreach (Comentario unCom in comenPostAmigo)
                                {
                                    comentarios.Add(unCom);
                                }
                            }
                            else if (unPost.Estado == "privado" && _sistema.SonAmigos(unMiem, unPost.Miembro))
                            {
                                post.Add(unPost);
                                List<Comentario> comenPostAmigo = unPost.ListaDeComentarios();

                                foreach (Comentario unCom in comenPostAmigo)
                                {
                                    comentarios.Add(unCom);
                                }
                            }
                            else
                            {
                                post.Add(unPost);
                                List<Comentario> comenPostAmigo = unPost.ListaDeComentarios();

                                foreach (Comentario unCom in comenPostAmigo)
                                {
                                    comentarios.Add(unCom);
                                }
                            }
                        }

                    }
                    ViewData["Posts"] = post;

                    ViewData["Comentarios"] = comentarios;

                    ViewData["userLogin"] = rol;

                }
                else
                {
                    ViewData["Posts"] = null;

                    ViewData["Comentarios"] = null;

                    ViewData["userLogin"] = rol;
                }

            }
            else
            {
                ViewData["Posts"] = null;

                ViewData["Comentarios"] = null;

                ViewData["userLogin"] = rol;
            }

            return View();
        }



        [Admin]
        public IActionResult ListarMiembros()
        {
            ViewBag.Miembros = _sistema.ListarMiembros();
            return View();
        }


        public IActionResult Login(string email, string password)
        {
            try
            {
                if (email!=null)
                {
                    if (password!=null)
                    {
                        Usuario unUsu = _sistema.ObtenerUsuario(email, password);
                        if (unUsu != null)
                        {
                            string rol = "";
                            // Roles validos son admin / miem 
                            if (unUsu.IsAdmin)
                            {
                                rol = "admin";
                            }
                            else if (!unUsu.IsAdmin)
                            {
                                rol = "miem";
                            }

                            // guardo los datos del usuario logueado
                            HttpContext.Session.SetString("email", email);
                            HttpContext.Session.SetString("rol", rol);

                            return RedirectToAction("Index");
                        }
                        else
                        {
                            throw new Exception($"El usuario no existe");
                        }
                        
                    }
                    else
                    {
                        throw new Exception($"La password es requerida");
                    }
                }
                else
                {
                    throw new Exception($"El email es requerido");
                }
            }
            catch (Exception e)
            {
                ViewBag.error = e.Message;
                return View("Index");
            }

            
        }


        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("index");
        }


        //muestra el formulario
        public IActionResult CreateMiembro()
        {
            return View();        //Esto garantiza que siempre haya un objeto Miembro en el modelo cuando la vista se renderice
        }


        [HttpPost]
        public IActionResult CrearMiembro(string email, string password, string nombre,
            string apellido, string fechaNacimiento)
        {

            try
            {
                if (fechaNacimiento != null)
                {
                    if (email != null)
                    {
                        if (password != null)
                        {
                            if (nombre != null)
                            {
                                if (apellido != null)
                                {
                                    DateTime fechaNac = DateTime.Parse(fechaNacimiento);
                                    Miembro nuevo = new Miembro(email, password, false, nombre, apellido, fechaNac);
                                    _sistema.CrearNuevoMiembro(nuevo);
                                    return RedirectToAction("index");
                                }
                                else
                                {
                                    throw new Exception($"El apellido es requerido");

                                }
                            }
                            else
                            {
                                throw new Exception($"El nombre es requerido");

                            }
                        }
                        else
                        {
                            throw new Exception($"La password es requerida");

                        }
                    }
                    else
                    {
                        throw new Exception($"El mail es requerido");

                    }
                }
                else
                {
                    throw new Exception($"La fecha esta vacia");
                }

            }
            catch (Exception e)
            {
                ViewBag.error = e.Message;
                return View("CreateMiembro");
            }
        }


        //Bloquear y activar un miembro
        [Admin]
        [HttpPost]
        public IActionResult BloquearMiembro(string email)     //tiene que ser el name de la vista
        {
            Miembro miembroABloquear = _sistema.ObtenerMiembro(email);

            if (miembroABloquear != null && !miembroABloquear.Bloqueado)
            {
                miembroABloquear.Bloqueado = true;
            }

            // Actualiza la página después de enviar la solicitud
            return RedirectToAction("ListarMiembros");
        }

        [Admin]
        [HttpPost]
        public IActionResult ActivarMiembro(string email)     //tiene que ser el name de la vista
        {
            Miembro miembroAactivar = _sistema.ObtenerMiembro(email);
            if (miembroAactivar != null && miembroAactivar.Bloqueado)
            {
                miembroAactivar.Bloqueado = false;
            }

            // Actualiza la página después de enviar la solicitud
            return RedirectToAction("ListarMiembros");
        }

        [Miem]
        public IActionResult VisualizarPublicacionesParaMiembro()
        {
            string email = HttpContext.Session.GetString("email");
            ViewData["Email"] = email;
            string rol = HttpContext.Session.GetString("rol");

            //Miembro unMiem = _sistema.ObtenerMiembro(email);

            return View();
        }

        [Miem]
        public IActionResult ListarMiembrosParaSolicitudAmistad()
        {
            string email = HttpContext.Session.GetString("email");
            ViewData["Email"] = email;
            string rol = HttpContext.Session.GetString("rol");
            //ViewBag es un objeto dinámico q se utiliza para pasar datos desde el controlador a la vista

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @if (@Context.Session.GetString("rol") == "miem")
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Usuario" asp-action="Saludo">Inicio</a>
                }
                else if (@Context.Session.GetString("rol") == null)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Usuario" asp-action="index">WebApp</a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Usuario" asp-action="Saludo">WebApp</a>
                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">

                        @* USUARIO ADMINISTRADOR *@
                        @if (@Context.Session.GetString("rol") == "admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" style="background-color: #86A789;" asp-area="" asp-controller="Usuario" asp-action="ListarMiembros">Lista Miembros</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" style="background-color: #B2C8BA;" asp-area="" asp-controller="Publicacion" asp-action="Index">Lista Posts</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" style="background-color: #D2E3C8;" asp-area="" asp-controller="Usuario" asp-action="logout">Logout</a>
                            </li>
                        }

                        @* USUARIO MIEMBRO *@
                        @if (@Context.Session.GetString("rol") == "miem")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" style="background-color: #F5EEC8;" asp-area="" asp-controller="Usuario" asp-action="ListarMiembrosParaSolicitudAmistad">Comunidad</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" style="background-color: #D0D4CA;" asp-area="" asp-controller="Publicacion" asp-action="VistaPublicar">Postear</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" style="background-color: #F5EEC8;" asp-area="" asp-controller="Usuario" asp-action="BuscadorParaMiembro">Buscar Post</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" style="background-color: #D0D4CA;" asp-area="" asp-controller="Usuario" asp-action="logout">Logout</a>
                            </li>
                        }

                        @* USUARIO ANONIMO *@
                        @if (@Context.Session.GetString("rol") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" style="background-color: #ECEE81;" asp-area="" asp-controller="Usuario" asp-action="CreateMiembro">Registro</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" style="background-color: #EDB7ED;" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>