WebApp/Controllers/ReaccionController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio1;

namespace WebApp.Controllers
{
    public class ReaccionController : Controller
    {
        private Sistema _sistema = Sistema.Instancia;
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Reaccionar(string objetoPost, string tipoReaccion)
        {
            string email = HttpContext.Session.GetString("email");
            string rol = HttpContext.Session.GetString("rol");

            Publicacion unPub = _sistema.ObtenerPublicacion(objetoPost);
            Miembro miembro = _sistema.ObtenerMiembro(email);
            Reaccion reaccion = _sistema.BuscarReaccion(unPub, miembro);

            if (reaccion == null)
            {
                Reaccion nueva = new Reaccion(tipoReaccion, miembro, unPub);
                _sistema.CrearNuevaReaccion(nueva);
                _sistema.ActualizarContadoresReacciones(nueva);
                return RedirectToAction("Saludo", "Usuario");
            }
            else
            {
                if (reaccion.TipoReaccion=="like")
                {
                    if (reaccion.TipoReaccion == tipoReaccion)
                    {
                        return RedirectToAction("Saludo", "Usuario");
                    }
                    else
                    {
                        reaccion.TipoReaccion = "dislike";
                        _sistema.ActualizarContadoresReacciones(reaccion, "actualizar");
                        return RedirectToAction("Saludo", "Usuario");
                    }
                    
                }
                else if (reaccion.TipoReaccion == "dislike")
                {
                    if (reaccion.TipoReaccion == tipoReaccion)
                    {
                        return RedirectToAction("Saludo", "Usuario");
                    }
                    else
                    {
                        reaccion.TipoReaccion = "like";
                        _sistema.ActualizarContadoresReacciones(reaccion, "actualizar");
                        return RedirectToAction("Saludo", "Usuario");
                    }
                }
            }
            return RedirectToAction("Saludo", "Usuario");
        }
    }
}

WebApp/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Obligatorio1;
using WebApp.Filtros;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace WebApp.Controllers
{
    public class UsuarioController : Controller
    {
        private Sistema _sistema = Sistema.Instancia;


        public IActionResult Index()
        {
            string email = HttpContext.Session.GetString("email");
            string rol = HttpContext.Session.GetString("rol");

            if (email != null)
            {
                return RedirectToAction("Saludo");
            }

            return View();
        }

        public IActionResult Saludo(string error = "")
        {
            if (error != "")
            {
                ViewBag.error = error;
            }
            string email = HttpContext.Session.GetString("email");
            // Obtengo el nombre de usuario desde el correo electrónico
            string nombreUsuario = email.Split('@')[0];
            string rol = HttpContext.Session.GetString("rol");

            Miembro unMiem = _sistema.ObtenerMiembro(email);

            // Paso el nombre de usuario a la vista
            ViewData["NombreUsuario"] = nombreUsuario;

            if (rol != null && rol == "miem")
            {
                List<Post> ListPublicacion = _sistema.ListarTodasLosPost();

                if (ListPublicacion.Count != 0)
                {
                    List<Comentario> comentarios = new List<Comentario>();

                    List<Post> post = new List<Post>();

                    foreach (Post unPost in ListPublicacion)
                    {
                        if (unPost.Miembro.Bloqueado == false && unPost.Censurado == false)
                        {
                            if (unMiem == unPost.Miembro)
                            {
                                post.Add(unPost);
                                List<Comentario> comenPostAmigo = unPost.ListaDeComentarios();

                                foreach (Comentario unCom in comenPostAmigo)
                                {
                                    comentarios.Add(unCom);
                                }
                            }
                            else if (unPost.Estado == "privado" && _sistema.SonAmigos(unMiem, unPost.Miembro))
                            {
                                post.Add(unPost);
                                List<Comentario> comenPostAmigo = unPost.ListaDeComentarios();

                                foreach (Comentario unCom in comenPostAmigo)
                                {
                                    comentarios.Add(unCom);
                                }
                            }
                            else
                            {
                                post.Add(unPost);
                                List<Comentario> comenPostAmigo = unPost.ListaDeComentarios();

                                foreach (Comentario unCom in comenPostAmigo)
                                {
                                    comentarios.Add(unCom);
                                }
                            }
                        }

                    }
                    ViewData["Posts"] = post;

                    ViewData["Comentarios"] = comentarios;

                    ViewData["userLogin"] = rol;

                }
                else
                {
                    ViewData["Posts"] = null;

                    ViewData["Comentarios"] = null;

                    ViewData["userLogin"] = rol;
                }

            }
            else
            {
                ViewData["Posts"] = null;

                ViewData["Comentarios"] = null;

                ViewData["userLogin"] = rol;
            }

            return View();
        }



        [Admin]
        public IActionResult ListarMiembros()
        {
            ViewBag.Miembros = _sistema.ListarMiembros();
            return View();
        }


        public IActionResult Login(string email, string password)
        {
            try
            {
                if (email!=null)
                {
                    if (password!=null)
                    {
                        Usuario unUsu = _sistema.ObtenerUsuario(email, password);
                        if (unUsu != null)
                        {
                            string rol = "";
                            // Roles validos son admin / miem 
                            if (unUsu.IsAdmin)
                            {
                                rol = "admin";
                            }
                            else if (!unUsu.IsAdmin)
                            {
                                rol = "miem";
                            }

                            // guardo los datos del usuario logueado
                            HttpContext.Session.SetString("email", email);
                            HttpContext.Session.SetString("rol", rol);

                            return RedirectToAction("Index");
                        }
                        else
                        {
                            throw new Exception($"El usuario no existe");
                        }
                        
                    }
                    else
                    {
                        throw new Exception($"La password es requerida");
                    }
                }
                else
                {
                    throw new Exception($"El email es requerido");
                }
            }
            catch (Exception e)
            {
                ViewBag.error = e.Message;
                return View("Index");
            }

            
        }


        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("index");
        }


        //muestra el formulario
        public IActionResult CreateMiembro()
        {
            return View();        //Esto garantiza que siempre haya un objeto Miembro en el modelo cuando la vista se renderice
        }


        [HttpPost]
        public IActionResult CrearMiembro(string email, string password, string nombre,
            string apellido, string fechaNacimiento)
        {

            try
            {
                if (fechaNacimiento != null)
                {
                    if (email != null)
                    {
                        if (password != null)
                        {
                            if (nombre != null)
                            {
                                if (apellido != null)
                                {
                                    DateTime fechaNac = DateTime.Parse(fechaNacimiento);
                                    Miembro nuevo = new Miembro(email, password, false, nombre, apellido, fechaNac);
                                    _sistema.CrearNuevoMiembro(nuevo);
                                    return RedirectToAction("index");
                                }
                                else
                                {
                                    throw new Exception($"El apellido es requerido");

                                }
                            }
                            else
                            {
                                throw new Exception($"El nombre es requerido");

                            }
                        }
                        else
                        {
                            throw new Exception($"La password es requerida");

                        }
                    }
                    else
                    {
                        throw new Exception($"El mail es requerido");

                    }
                }
                else
                {
                    throw new Exception($"La fecha esta vacia");
                }

            }
            catch (Exception e)
            {
                ViewBag.error = e.Message;
                return View("CreateMiembro");
            }
        }


        //Bloquear y activar un miembro
        [Admin]
        [HttpPost]
        public IActionResult BloquearMiembro(string email)     //tiene que ser el name de la vista
        {
            Miembro miembroABloquear = _sistema.ObtenerMiembro(email);

            if (miembroABloquear != null && !miembroABloquear.Bloqueado)
            {
                miembroABloquear.Bloqueado = true;
            }

            // Actualiza la página después de enviar la solicitud
            return RedirectToAction("ListarMiembros");
        }

        [Admin]
        [HttpPost]
        public IActionResult ActivarMiembro(string email)     //tiene que ser el name de la vista
        {
            Miembro miembroAactivar = _sistema.ObtenerMiembro(email);
            if (miembroAactivar != null && miembroAactivar.Bloqueado)
            {
                miembroAactivar.Bloqueado = false;
            }

            // Actualiza la página después de enviar la solicitud
            return RedirectToAction("ListarMiembros");
        }

        [Miem]
        public IActionResult VisualizarPublicacionesParaMiembro()
        {
            string email = HttpContext.Session.GetString("email");
            ViewData["Email"] = email;
            string rol = HttpContext.Session.GetString("rol");

            //Miembro unMiem = _sistema.ObtenerMiembro(email);

            return View();
        }

        [Miem]
        public IActionResult ListarMiembrosParaSolicitudAmistad()
        {
            string email = HttpContext.Session.GetString("email");
            ViewData["Email"] = email;
            string rol = HttpContext.Session.GetString("rol");
            //ViewBag es un objeto dinámico q se utiliza para pasar datos desde el controlador a la vista

WebApp/Views/Usuario/BuscadorParaMiembro.cshtml
@using Obligatorio1;
@model dynamic;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@ViewBag.error

<h1>Buscador</h1>

<div class="container mt-5">

    <form action="FiltrarPublicaciones" method="post">
        <input type="text" name="texto" placeholder="Texto" />
        <input type="number" name="valorAceptacion" placeholder="Valor de aceptación" />
        <button type="submit" class="btn btn-success">Buscar</button>
    </form>

 </div>

WebApp/Views/Usuario/CreateMiembro.cshtml
@using Obligatorio1;
@model dynamic;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="container mt-5">
    <h1>Registro de Miembro</h1>

        @using (Html.BeginForm("CrearMiembro", "Usuario", FormMethod.Post))
        {
            <div class="contenedor">
                <input type="email" placeholder="Ingrese mail" name="email" /><br />
                <input type="password" placeholder="Ingrese password" name="password" /><br />
                <input type="text" placeholder="Ingrese su nombre" name="nombre" /><br />
                <input type="text" placeholder="Ingrese el apellido" name="apellido" /><br />

                <label for="fechaNacimiento">Fecha de Nacimiento:</label>
                <input type="date" id="fechaNacimiento" name="fechaNacimiento" /><br />
                @ViewBag.error

            <div class="alinearDerecha"><button type="submit" class="btn btn-success">Alta</button></div>
            </div>
        }
</div>

<style>
 
    .contenedor {
        width: 100%;
        text-align: center;
        display: flex;
        flex-direction: column;
    }

    .alinearDerecha {
        text-align: end;
    }
</style>

WebApp/Views/Usuario/FiltrarPublicaciones.cshtml
@using Obligatorio1;
@model dynamic;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@ViewBag.error

@{
    List<Post> posts = ViewBag.PostFiltrados ?? new List<Post>();
    List<Comentario> comentarios = ViewBag.ComentariosFiltrados ?? new List<Comentario>();
}

<h1>Resultados de la búsqueda</h1>

@if (!posts.Any() && !comentarios.Any())
{
    <p>
        No existen resultados 😔
    </p>
}
else
{
    if (posts.Any())
    {
        <h2>POST: </h2>
        @foreach (Post unPost in posts)
        {
            <div class="UnaLinea">
                <h4>@unPost.Titulo</h4>
                <p>@unPost.Contenido</p>
                <p><em>Autor: @unPost.Miembro.Nombre @unPost.Miembro.Apellido</em></p>
                <p>VA: @unPost.VA</p>
            </div>
        }
    }

    if (comentarios.Any())
    {
        <h2>COMENTARIOS: </h2>
        @foreach (Comentario comentario in comentarios)
        {
            <div>
                <h5>@comentario.Titulo</h5>
                <p>@comentario.Contenido</p>
                <p><em>Autor: del Comentario: @comentario.Miembro.Nombre @comentario.Miembro.Apellido</em></p>
                <p>VA: @comentario.VA</p>
            </div>
        }
    }

}

<style>
    .UnaLinea {
        display: flex;
        gap: 10px;
        margin-bottom: 20px;
    }
</style>

WebApp/Views/Usuario/Index.cshtml
@using Obligatorio1;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Login</h1>

<form action="/usuario/login" method="post">
    <input type="email" name="email" placeholder="Ingrese mail" />
    <input type="password" name="password" placeholder="Ingrese password" />
    <button type="submit">Login</button>
</form>
@ViewBag.error

WebApp/Views/Usuario/ListarMiembros.cshtml
@using Obligatorio1;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Lista de Miembros</h1>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Email</th>
            <th scope="col">Password</th>
            <th scope="col">nombre</th>
            <th scope="col">apellido</th>
            <th scope="col">Acción</th>
            <th scope="col">Acción</th>
        </tr>
    </thead>

    <tbody>
        @foreach (Miembro unU in ViewBag.Miembros)
        {
            <tr>
                <th scope="row">@unU.Email</th>
                <td>@unU.Password</td>
                <td>@unU.Nombre</td>
                <td>@unU.Apellido</td>
                <td>
                    @if (!unU.Bloqueado)
                    {
                        <form method="post" asp-action="BloquearMiembro">
                            <input type="hidden" name="email" value="@unU.Email" />
                            <button type="submit" class="btn btn-danger">
                                Bloquear
                            </button>
                        </form>
                    }
                    else
                    {
                        <form method="post" asp-action="ActivarMiembro">
                            <input type="hidden" name="email" value="@unU.Email" />
                            <button type="submit" class="btn btn-success">
                                Activar
                            </button>
                        </form>
                    }
                </td>
                <td>
                    <button type="button" class="btn btn-info">
                        @Html.ActionLink("Ver publicacion", "Index", "Publicacion", new { email = unU.Email })
                    </button>
                </td>

            </tr>
        }

    </tbody>
</table>

WebApp/Views/Usuario/ListarMiembrosParaSolicitudAmistad.cshtml
@using Obligatorio1;
@model dynamic;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@ViewBag.error

@{
    string emailUsuarioLog = ViewData["Email"].ToString();
}


<h1>Lista de Miembros</h1>

<table class="table table-striped table-hover">

    <thead>
        <tr>
            <th scope="col">Email</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Estado</th>
        </tr>
    </thead>


    <tbody>
        @foreach (Miembro unU in ViewBag.Miembros)
        {
            bool tieneSolicitudPendienteEnviada = false;
            bool tieneSolicitudPendienteRecibida = false;
            bool tieneSolicitudRechazada = false;
            bool sonAmigos = false;
            Invitacion unaInvita = new Invitacion();

            foreach (Invitacion unaI in ViewBag.Invitaciones)
            {
                if (unaI.MiembroSolicitado.Email == unU.Email && unaI.Estado == "proceso")
                {
                    tieneSolicitudPendienteEnviada = true;
                    break;
                }
                else if (unaI.MiembroSolicitante.Email == unU.Email && unaI.Estado == "proceso")
                {
                    tieneSolicitudPendienteRecibida = true;
                    unaInvita = unaI;
                    break;
                }
                else if ((unaI.MiembroSolicitado.Email == unU.Email || unaI.MiembroSolicitante.Email == unU.Email) && unaI.Estado == "rechazada")
                {
                    tieneSolicitudRechazada = true;
                    break;
                }
                else if ((unaI.MiembroSolicitado.Email == unU.Email || unaI.MiembroSolicitante.Email == unU.Email) && unaI.Estado == "aprobada")
                {
                    sonAmigos = true;
                    break;
                }
            }

            <tr>
                <th scope="row">@unU.Email</th>
                <td>@unU.Nombre</td>
                <td>@unU.Apellido</td>
                <td>
                    @* Solicitud pendiente, enviada por el Usuario Log *@
                    @if (tieneSolicitudPendienteEnviada)
                    {
                        <span class="text-warning">Solicitud ya enviada</span>
                    }
                    @* Solicitud pendiente de aprobacion, recibida por el Usuario Log *@
                    else if (tieneSolicitudPendienteRecibida)
                    {
                        <form method="post" asp-action="AceptarSolicitudAmistad">
                            <input type="hidden" name="IDInvitacion" value="@unaInvita.Id" />
                            <button type="submit" class="btn btn-success">
                                Aceptar solicitud de amistad 💛
                            </button>
                        </form>

                        <form method="post" asp-action="RechazarSolicitudAmistad">
                            <input type="hidden" name="IDInvitacion" value="@unaInvita.Id" />
                            <button type="submit" class="btn btn-dark">
                                Rechazar solicitud de amistad 💔
                            </button>
                        </form>
                    }
                    else if (tieneSolicitudRechazada)
                    {
                        <span class="text-danger">Solicitud rechazada</span>
                    }
                    else if (sonAmigos)
                    {
                        <span class="text-success">Amigos! 👯</span>
                    }
                    else
                    {
                        <form method="post" asp-action="EnviarSolicitudAmistad">
                            <input type="hidden" name="emailAmigo" value="@unU.Email" />
                            <button type="submit" class="btn btn-primary">
                                Enviar solicitud de amistad 💛
                            </button>
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>


</table>

WebApp/Views/Usuario/Saludo.cshtml
@using Obligatorio1;
@model dynamic
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    //Layout = null;
}


<h2>Hola, @ViewData["NombreUsuario"]</h2>
<div class="error">@ViewBag.error</div>

@{
    List<Post> publicaciones = ViewData["Posts"] as List<Post>;
    List<Comentario> comentarios = ViewData["Comentarios"] as List<Comentario>;
    string rol = ViewData["userLogin"] as string;
}

@if (publicaciones != null)
{
    @foreach (var unaPub in publicaciones)
    {
        <div class="container mt-5">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">@unaPub.Titulo</h5>
                    <p class="card-text">Fecha: @unaPub.Fecha.ToShortDateString() - Autor: @unaPub.Miembro.Nombre @unaPub.Miembro.Apellido</p>
                </div>
                <div class="card-body">
                    <p class="card-text">@unaPub.Contenido</p>
                </div>

                <div class="card-footer-post">



                    @using (Html.BeginForm("Reaccionar", "Reaccion", FormMethod.Post))
                    {
                           <span>👍: @unaPub.CdadLike </span>
                        <input type="hidden" id="objetoPost" name="objetoPost" value="@unaPub.Id" />
                        <input type="hidden" id="tipoReaccion" name="tipoReaccion" value="like" />
                        <button type="submit" class="btn btn-success">Like</button>
                    }

                    @using (Html.BeginForm("Reaccionar", "Reaccion", FormMethod.Post))
                    {
                        <span>👎: @unaPub.CdadDislike </span>
                        <input type="hidden" id="objetoPost" name="objetoPost" value="@unaPub.Id" />
                        <input type="hidden" id="tipoReaccion" name="tipoReaccion" value="dislike" />
                        <button type="submit" class="btn btn-danger">Dislike</button>

                        <span>VA: @unaPub.VA </span>
                    }
                </div>

                


                @if (comentarios != null)
                {
                    @foreach (Comentario comentario in comentarios)
                    {
                        @if (comentario.Post == unaPub)
                        {
                            <!-- Sección de comentarios -->
                            <div class="card-footer">
                                <div class="nested-comment">
                                    <div class="titulo-comentario">
                                        <h5 class="card-title">@comentario.Titulo</h5>
                                        <p>Fecha: @comentario.Fecha.ToShortDateString() - Autor: @comentario.Miembro.Nombre @comentario.Miembro.Apellido</p>
                                    </div>
                                    <div class="contendio-comentario">
                                        <p class="card-text">@comentario.Contenido</p>
                                        <div class="reaccion-comentario">
                                            @using (Html.BeginForm("Reaccionar", "Reaccion", FormMethod.Post))
                                            {
                                                <span>👍: @comentario.CdadLike </span>
                                                <input type="hidden" id="objetoPost" name="objetoPost" value="@comentario.Id" />
                                                <input type="hidden" id="tipoReaccion" name="tipoReaccion" value="like" />
                                                <button type="submit" class="btn btn-success">Like</button>
                                                <span>👍: @comentario.CdadLike </span>
                                            }

                                            @using (Html.BeginForm("Reaccionar", "Reaccion", FormMethod.Post))
                                            {
                                                <span>👎: @comentario.CdadDislike </span>
                                                <input type="hidden" id="objetoPost" name="objetoPost" value="@comentario.Id" />
                                                <input type="hidden" id="tipoReaccion" name="tipoReaccion" value="dislike" />
                                                <button type="submit" class="btn btn-danger">Dislike</button>

                                                <span>VA: @comentario.VA </span>
                                            }
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        }
                    }
                }

                <div class="card-footer-comentar">
                    <div class="nested-comment">
                        <h5 class="card-title">Comentar</h5>
                        @using (Html.BeginForm("Comentar", "Publicacion", FormMethod.Post))
                        {
                            <input type="hidden" id="objetoComentario" name="objetoComentario" value="@unaPub.Id" />
                            <input type="text" id="titulo" name="titulo" placeholder="Titulo del comentario" />
                            <textarea id="comentario" name="comentario" placeholder="Ingrese su comentario"></textarea>
                            <div class="alinearDerecha"><button type="submit" class="btn btn-primary">Comentar</button></div>
                        }
                        
                    </div>
                </div>
            </div>
        </div>

        <br />

    }

}
else if (rol == "miem")
{
    <h1>No hay comentarios!</h1>
}



<style>
    #comentario{
        width: 100%;
    }

    .alinearDerecha{
        text-align:end;
    }

    .card-footer{
        background-color: rgb(69 153 64 / 15%) !important;
    }

    .card-footer-comentar{
        padding: 0.5rem 1rem;
        background-color: rgb(93 96 199 / 22%);
        border-top: 1px solid rgba(0,0,0,.125);
    }

    .card-footer-post {
        display: flex;
        align-items: end;
        gap: 10px;
        padding: 0.5rem 1rem;
        background-color: rgba(0,0,0,.03);
        border-top: 1px solid rgba(0,0,0,.125);
    }

    .reaccion-comentario {
        display: flex;
        align-items: end;
        gap: 10px;
    }

    .contendio-comentario{
        width:100%;
        display: flex;
        justify-content:space-between;
    }

    .titulo-comentario {
        display: flex;
        justify-content: space-between;
    }

    .card-header {
        display: flex;
        justify-content: space-between;
    }

    .error{
        color: red;
    }
</style>

WebApp/Views/Usuario/VisualizarPublicacionesParaMiembro.cshtml
@using Obligatorio1;

@model Sistema;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@ViewBag.error


    @{
        List<Publicacion> publicaciones = ViewData["Posts"] as List<Publicacion>;
        List<Comentario> comentarios = ViewData["Comentarios"] as List<Comentario>;
    }
    @if (publicaciones != null)
    {
        @foreach (var unaPub in publicaciones)
        {
            
            <div>
                <div class="UnaLinea">
                    <h3>@unaPub.Titulo</h3>
                    <p>Fecha: @unaPub.Fecha.ToShortDateString()</p>
                    <p>@unaPub.Contenido</p>
                    <p><em>Autor: @unaPub.Miembro.Nombre @unaPub.Miembro.Apellido</em></p>
                </div>

                @if (comentarios != null)
                {
                    @foreach (Comentario comentario in comentarios)
                    {
                        @if (comentario.Post == unaPub)
                        {
                            <div>
                                <p>Comentario: @comentario.Titulo</p>
                                <p>@comentario.Contenido</p>
                                <p>Fecha del Comentario: @comentario.Fecha.ToShortDateString()</p>
                                <p>Autor del Comentario: @comentario.Miembro.Nombre @comentario.Miembro.Apellido</p>
                            </div>
                        }
                    }
                }

            </div>
            
        }
    }

<style>
    .UnaLinea{
        display: flex;
        gap: 10px;
        margin-bottom: 20px;
    }
</style>